In [1]:
import sympy as sp 
import numpy as np 
sp.init_printing(pretty_print=True)

In [2]:
x,y,a,b = sp.symbols('x y a b ')

In [3]:
def derivada_simbolica(fun):
    derivative = sp.diff(fun,x)
    res = derivative
    return res

In [4]:
valor = derivada_simbolica(x**2)
valor

Resolva a restrição abaixo utilizando o pacote sympy:
$$
\begin{cases}
a = x +1\\
b = 4x^2 + 5 \\
restrição: a = b
\end{cases}
$$

 

In [5]:
eq_a = sp.Eq(a, x +1 )
eq_b = sp.Eq(b,4*x**2 + 5)

In [6]:
z = sp.Eq(eq_a.rhs,eq_b.rhs)

In [7]:
sp.solve(z,dict = True)

In [10]:
fun = x**4 + sp.cos(x) + 34*x

fun_res = sp.lambdify(x,fun,'numpy')


In [50]:
k = np.linspace(0,30,30)
j = np.arange(0,30+1,1)
k

array([ 0.        ,  1.03448276,  2.06896552,  3.10344828,  4.13793103,
        5.17241379,  6.20689655,  7.24137931,  8.27586207,  9.31034483,
       10.34482759, 11.37931034, 12.4137931 , 13.44827586, 14.48275862,
       15.51724138, 16.55172414, 17.5862069 , 18.62068966, 19.65517241,
       20.68965517, 21.72413793, 22.75862069, 23.79310345, 24.82758621,
       25.86206897, 26.89655172, 27.93103448, 28.96551724, 30.        ])

In [51]:

fun_res(k)

array([1.00000000e+00, 3.68286152e+01, 8.81907027e+01, 1.97281665e+02,
       4.33325365e+02, 8.92075302e+02, 1.69625072e+03, 2.99648110e+03,
       4.97183527e+03, 7.82941768e+03, 1.18034266e+04, 1.71545954e+04,
       2.41705636e+04, 3.31668145e+04, 4.44872622e+04, 5.85039146e+04,
       7.56159410e+04, 9.62490570e+04, 1.20855828e+05, 1.49916594e+05,
       1.83940114e+05, 2.23463291e+05, 2.69050265e+05, 3.21291733e+05,
       3.80805192e+05, 4.48235845e+05, 5.24257290e+05, 6.09571326e+05,
       7.04907052e+05, 8.11020154e+05])

In [52]:
fun_res(j) 

array([1.00000000e+00, 3.55403023e+01, 8.35838532e+01, 1.82010008e+02,
       3.91346356e+02, 7.95283662e+02, 1.50096017e+03, 2.63975390e+03,
       4.36785450e+03, 6.86608887e+03, 1.03391609e+04, 1.50150044e+04,
       2.11448439e+04, 2.90039074e+04, 3.88921367e+04, 5.11342403e+04,
       6.60790423e+04, 8.40987248e+04, 1.05588660e+05, 1.30967989e+05,
       1.60680408e+05, 1.95194452e+05, 2.35003000e+05, 2.80622467e+05,
       3.32592424e+05, 3.91475991e+05, 4.57860647e+05, 5.32358708e+05,
       6.15607037e+05, 7.08266252e+05, 8.11020154e+05])

In [56]:
l= np.sum(fun_res(k))

In [57]:
m = np.sum(fun_res(j))

In [60]:
(l+m)*1e-26